# Generated by Django 2.2.7 on 2019-11-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFConverter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.TimeField(auto_now=True)),
                ('size', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('userName', models.CharField(max_length=100)),
                ('regDate', models.DateField(auto_now=True)),
                ('uploadCount', models.IntegerField()),
            ],
        ),
    ]
