# Generated by Django 2.2.7 on 2019-11-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docxtopdf', '0002_auto_20191126_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('userName', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='pdfconverter',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pdfconverter',
            name='userName',
        ),
    ]
