# Generated by Django 2.2.7 on 2019-12-09 16:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('docxtopdf', '0003_auto_20191126_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='email',
        ),
        migrations.AddField(
            model_name='pdfconverter',
            name='user',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='docxtopdf.UserInfo'),
            preserve_default=False,
        ),
    ]
